### ISSUE TITLE
[Bug] Uncaught Error: Cannot find module 'onnxruntime-node'

### ISSUE THREAD

**Issue by jlia0** [xenova/transformers.js#213]
This bug happens after I upgrade the package from 1.4.3 to 2.4.2.

I am using Next.js, is it due the client/server side issue?

<img width="796" alt="image" src="https://github.com/xenova/transformers.js/assets/24471281/dee502f4-16ff-4867-9580-3a0eb7ea37f4">

**Comment by xenova** [comment]
Can you post your next config file?

I am busy working on a next.js example application, which you can find here: https://github.com/xenova/transformers.js/pull/211

**Comment by jlia0** [comment]
Yes I followed that example...

`/** @type {import("next").NextConfig} */
const nextConfig = {
    // Override the default webpack configuration
    webpack: (config) => {
        // Ignore node-specific modules when bundling for the browser
        // https://webpack.js.org/configuration/resolve/#resolvealias
        config.resolve.alias = {
            ...config.resolve.alias,
            sharp$: false,
            "onnxruntime-node$": false,
        };
        return config;
    },
};

module.exports = nextConfig;
`

**Comment by xenova** [comment]
> I am not using the App router.

The above tutorial was designed for the app router. So that might explain why that config is causing an issue.

From [the previous solution](https://github.com/xenova/transformers.js/issues/98#issuecomment-1519367516) (which worked for v1.4.3), just remember to remove the part where you use the `IgnorePlugin`

**Comment by jlia0** [comment]
I got it working using your next.config! It turns out it's some other issues... Also how can I use the models on the server-side?

**Comment by xenova** [comment]
> Also how can I use the models on the server-side?

Working on that! I think it should be possible by:
1. Using [node-loader](https://github.com/webpack-contrib/node-loader) or [webpack-asset-relocator-loader](https://github.com/vercel/webpack-asset-relocator-loader)
2. Updating config to separate server and client bundling (work in progress).
```js
// Override the default webpack configuration
webpack: (config, { buildId, dev, isServer, defaultLoaders, nextRuntime, webpack }) => {
    if (isServer) {
        // TODO...
    } else {
        // Ignore node-specific modules when bundling for the browser
        // https://webpack.js.org/configuration/resolve/#resolvealias
        config.resolve.alias = {
            ...config.resolve.alias,
            "sharp$": false,
            "onnxruntime-node$": false,
        }
    }

    return config;
},
```
4.

**Comment by jlia0** [comment]
That's great! Does server-side support mean that the models could run on the serverless functions within Vercel hosting?

**Comment by xenova** [comment]
> Does server-side support mean that the models could run on the serverless functions within Vercel hosting?

I haven't tested it yet, but if they can run normal node packages, then it should be possible 👍

**Comment by xenova** [comment]
Got server-side working 👍  PR: https://github.com/xenova/transformers.js/pull/211 (will merge into main soon)

Demo app: https://huggingface.co/spaces/Xenova/next-server-example-app
